### ISSUE TITLE
组件中不可以使用ButterKnife吗？

### ISSUE THREAD

**Issue by qiaop** [luojilab/DDComponentForAndroid#54]
使用ButterKnife会出现空指针异常。
`12-04 14:06:04.123 5233-5233/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.lxkj.yunhetong.component.testmoudle, PID: 5233
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lxkj.yunhetong.component.testmoudle/com.lxkj.yunhetong.component.testmoudle.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                     at com.lxkj.yunhetong.component.testmoudle.MainActivity.onCreate(MainActivity.java:21)
                                                     at android.app.Activity.performCreate(Activity.java:6956)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) `

**Comment by weinierfei** [comment]
看 [issue39](https://github.com/luojilab/DDComponentForAndroid/issues/39)  的最后

**Comment by qiaop** [comment]
谢谢!
