### ISSUE TITLE
编译版本升级到1.8报错

### ISSUE THREAD

**Issue by Yanqilong** [luojilab/DDComponentForAndroid#79]
昨天碰到一个问题，JDK的坑，RxAndroid 使用 compose 操作符 JDK1.8 以下不能自动转换泛型，结果将编译版本果断升级到1.8，今天运行项目，就报下面信息错误了，大大可以将编译版本升级到1.8么

```ruby
Information:Gradle tasks [:welcome:assembleDebug]
Warning:Supported source version 'RELEASE_7' from annotation processor 'com.luojilab.router.compiler.processor.AutowiredProcessor' less than -source '1.8'
Warning:Supported source version 'RELEASE_7' from annotation processor 'com.luojilab.router.compiler.processor.RouterProcessor' less than -source '1.8'
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/MenuRes;
Error:com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/MenuRes;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':welcome:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/MenuRes;
```

**Comment by Yanqilong** [comment]
框架只会出现⚠️警告信息，问题不是框架引起的
